---
# tasks file for nfs
- name: Install Pre-setup
  import_tasks: requirement.yml
  when: ansible_facts['distribution'] == 'RedHat'

- name: Configure Server
  import_tasks: nfs-server.yml
  when: ansible_facts['distribution'] == 'RedHat'

- name: Configure Client
  import_tasks: nfs-client.yml
  when: ansible_facts['distribution'] == 'RedHat'
