---
- name: Configuring nfs-client
  ansible.builtin.debug:
    msg: "NFS client: {{ nfs_client_ip }}"

- name: Verify NFS share
  ansible.builtin.command:
    name: "showmount -e {{ nfs_server_ip }}"
  register: showmount


- name: Create directory on client
  ansible.builtin.file:
    path: "{{ nfs_client_dir }}"
    state: directory
    mode: '0777'

- name: Mount server with client
  ansible.posix.mount:
    src: "{{ nfs_server_ip }}:{{ nfs_server_dir }}"
    path: "{{ nfs_client_dir }}"
    fstype: nfs
    state: mounted
