---
- name: Configuring nfs-server
  ansible.builtin.debug:
    msg: "NFS server: {{ nfs_server_ip }}"

- name: Create a directory on server
  ansible.builtin.file:
    path: "{{ nfs_server_dir }}"
    state: directory 
    mode: '0777'

- name: Change Configuration of nfs-server
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ nfs_server_dir }} {{ nfs_client_ip }}(rw,sync,no_root_squash)"

- name: Mount the file system
  ansible.builtin.command:
    cmd: exportfs -r

- name: Reloading firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded


